### ISSUE TITLE
Add line numbers to output

### ISSUE THREAD

**Issue by maurelian** [federicobond/eth-mutants#14]
It would be helpful for understanding what's being mutated.

![image](https://user-images.githubusercontent.com/23033765/44151370-5de23120-a070-11e8-8e58-e52a99260283.png)

**Comment by federicobond** [comment]
Yes! Great idea.

**Comment by federicobond** [comment]
Done. It looks like this right now, let's see how it works.

<img width="497" alt="captura de pantalla 2018-08-15 a la s 16 00 00" src="https://user-images.githubusercontent.com/138426/44167395-5ff87800-a0a4-11e8-8588-e0b8bc44f22f.png">

**Comment by maurelian** [comment]
oh, nice. Alternatively you could just append it to the file path like `contracts/math/SafeMath.sol:20`
