### ISSUE TITLE
Add Event remover mutator

### ISSUE THREAD

**Issue by federicobond** [federicobond/eth-mutants#5]
This mutator removes an Event emit from your contract.

**Comment by yxliang01** [comment]
@federicobond I am curious what use of such mutator is. Since events are not affecting the executions except the impact of the gas usage (correct me if wrong)?

**Comment by federicobond** [comment]
They don't affect the execution, but they are part of the expected interface for users of the contract. Tests should ensure that the contract emits the right events at the right time.

**Comment by yxliang01** [comment]
@federicobond I see. Thanks for good explanation :) By the way, I think this issue can be closed by https://github.com/federicobond/eth-mutants/blob/4c56f136581a8365d527f61f20de9f674dcaa043/src/mutators/event-eliminator.js ?

**Comment by federicobond** [comment]
You are right. Thanks!
